// <auto-generated />
using CatalogoRoupas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogoRoupas.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogoRoupas.Models.CatalogoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Feminino")
                        .HasColumnType("bit")
                        .HasColumnName("Feminino");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Marca");

                    b.Property<bool>("Masculino")
                        .HasColumnType("bit")
                        .HasColumnName("Masculino");

                    b.Property<string>("Peca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Peca");

                    b.HasKey("Id");

                    b.ToTable("Catalogo");
                });
#pragma warning restore 612, 618
        }
    }
}
